### ISSUE TITLE
tokenize的问题

### ISSUE THREAD

**Issue by zzy99** [jiangxiaoshuaiya/BertHub#1]
好像发现一个小问题：在tokenize的时候，context在前，qa-pair在后，但context平均长度一千多，导致大部分tokenize截断后没有qa的信息在里面，如果换个顺序也许会好些

**Comment by jiangxiaoshuaiya** [comment]
> 好像发现一个小问题：在tokenize的时候，context在前，qa-pair在后，但context平均长度一千多，导致大部分tokenize截断后没有qa的信息在里面，如果换个顺序也许会好些

这里仅提供最基本的baseline，帮助尽快上手，后续提升还需要选手自行brainstorm
